<!-- ======================
       3. Gazebo Plugin
  ====================== -->

  <!-- Pose Publisher Plugin -->
  <gazebo>
    <plugin filename="ignition-gazebo-pose-publisher-system"
            name="ignition::gazebo::systems::PosePublisher">
      <publish_link_pose>true</publish_link_pose>
      <publish_sensor_pose>true</publish_sensor_pose>
    </plugin>
  </gazebo>

  <!-- Joint states plugin -->
  <gazebo>
    <plugin 
      filename="ignition-gazebo-joint-state-publisher-system" 
      name="ignition::gazebo::systems::JointStatePublisher">
      <robotNamespace>/model/variable_tilt_hexacopter</robotNamespace>
    </plugin>
  </gazebo>

  <!-- Multicopter motor model plugin -->
  <xacro:macro name="motor_plugin" params="id joint link direction">
    <gazebo>
      <plugin name="ignition::gazebo::systems::MulticopterMotorModel"
              filename="ignition-gazebo-multicopter-motor-model-system">
        <jointName>${joint}</jointName>
        <linkName>${link}</linkName>
        <turningDirection>${direction}</turningDirection>
        <timeConstantUp>0.0125</timeConstantUp>
        <timeConstantDown>0.025</timeConstantDown>
        <maxRotVelocity>800.0</maxRotVelocity>
        <motorConstant>8.54858e-06</motorConstant>
        <momentConstant>0.016</momentConstant>
        <commandSubTopic>command/motor_speed</commandSubTopic>
        <motorNumber>${id}</motorNumber>
        <rotorDragCoefficient>8.06428e-05</rotorDragCoefficient>
        <rollingMomentCoefficient>1e-06</rollingMomentCoefficient>
        <motorSpeedPubTopic>motor_speed/${id}</motorSpeedPubTopic>
        <rotorVelocitySlowdownSim>10</rotorVelocitySlowdownSim>
        <motorType>velocity</motorType>
      </plugin>
    </gazebo>
  </xacro:macro>

  <!-- Lift and drag plugin -->
  <xacro:macro name="lift_drag_plugin" params="blade_id link_name upward_x upward_y">
    <gazebo>
      <plugin
        filename="ignition-gazebo-lift-drag-system"
        name="ignition::gazebo::systems::LiftDrag">
        <a0>0.2</a0>
        <cla>10.0</cla>
        <cda>0.0001</cda>
        <cma>0.00</cma>
        <alpha_stall>10.0</alpha_stall>
        <cla_stall>1.0</cla_stall>
        <cda_stall>0.001</cda_stall>
        <cma_stall>0.0</cma_stall>
        <cp>${prop_box_length/2} 0 0</cp>
        <area>${prop_box_length * prop_box_width}</area>
        <air_density>1.2041</air_density>
        <forward>0 0 -1</forward>
        <upward>${upward_x} ${upward_y} 0</upward>
        <link_name>${link_name}</link_name>
      </plugin>
    </gazebo>
  </xacro:macro>

  <!-- Joint controller plugin -->
  <xacro:macro name="joint_controller_plugin" params="joint">
    <gazebo>
      <plugin filename="ignition-gazebo-joint-controller-system"
              name="ignition::gazebo::systems::JointController">
        <joint_name>${joint}</joint_name>
        <!-- <commandTopic>/hexacopter/${joint}/position_cmd</commandTopic> -->
        <use_force_commands>false</use_force_commands>
        <!-- <minPosition>-1.57</minPosition>
        <maxPosition>1.57</maxPosition> -->
      </plugin>
    </gazebo>
  </xacro:macro>

  <!-- Plugins for motors -->
  <xacro:motor_plugin id="1" joint="joint_prop_1" link="prop_1" direction="ccw"/>
  <xacro:motor_plugin id="2" joint="joint_prop_2" link="prop_2" direction="cw"/>
  <xacro:motor_plugin id="3" joint="joint_prop_3" link="prop_3" direction="ccw"/>
  <xacro:motor_plugin id="4" joint="joint_prop_4" link="prop_4" direction="cw"/>
  <xacro:motor_plugin id="5" joint="joint_prop_5" link="prop_5" direction="ccw"/>
  <xacro:motor_plugin id="6" joint="joint_prop_6" link="prop_6" direction="cw"/>

  <!-- Lift Drag Plugins -->
  <xacro:lift_drag_plugin blade_id="1" link_name="prop_1" upward_x="0.0" upward_y="1.0" />
  <xacro:lift_drag_plugin blade_id="2" link_name="prop_2" upward_x="0.866" upward_y="-0.5" />
  <xacro:lift_drag_plugin blade_id="3" link_name="prop_3" upward_x="-0.866" upward_y="-0.5" />
  <xacro:lift_drag_plugin blade_id="4" link_name="prop_4" upward_x="0.0" upward_y="-1.0" />
  <xacro:lift_drag_plugin blade_id="5" link_name="prop_5" upward_x="0.866" upward_y="0.5" />
  <xacro:lift_drag_plugin blade_id="6" link_name="prop_6" upward_x="-0.866" upward_y="0.5" />

  <!-- Joint Controllers -->
  <xacro:joint_controller_plugin joint="joint_arm_1"/>
  <xacro:joint_controller_plugin joint="joint_arm_2"/>
  <xacro:joint_controller_plugin joint="joint_arm_3"/>
  <xacro:joint_controller_plugin joint="joint_arm_4"/>
  <xacro:joint_controller_plugin joint="joint_arm_5"/>
  <xacro:joint_controller_plugin joint="joint_arm_6"/>

  <!-- IMU and Odometry Plugins -->
  <!-- <gazebo>
    <plugin filename="ignition-gazebo-imu-system"
            name="ignition::gazebo::systems::Imu">
      <topic>/hexacopter/imu</topic>
      <link_name>base</link_name>
    </plugin>
  </gazebo> -->

  

  <!-- <gazebo>
    <plugin filename="ignition-gazebo-odometry-publisher-system"
            name="ignition::gazebo::systems::OdometryPublisher">
      <topic>/hexacopter/odom</topic>
    </plugin>
  </gazebo> -->